### PR TITLE
Fix sandbox guessing logic.

### PR DESCRIPTION
**Pull request by abhinav**
07456a76825f6579bee1efdafca2998a144750cc broke ghc-mod for OSX.

It assumed package dbs were under `x86_64-darwin-ghc-7.8.3-packages.conf.d`,
but GHC 7.8.3 on OSX uses `x86_64-osx-ghc-7.8.3-packages.conf.d` (`osx`
instead of `darwin`).

This commit changes the logic to actually check for package db existence. If
the db that cabal.sandbox.config points to already exists, then there's
nothing to fix. If it doesn't exist, it looks for other package dbs in the
sandbox directory and uses the first of those.

(I'm not sure whether pull requests should go to this repository or Kazu's repository.)

### CODE REVIEW

**Comment by DanielG** [comment]
Have you checked the Cabal source to see what it actually does? I'd like the logic to be more in line with what Cabal does rather than just guessing really.

Either way the real bug here seems to be that we use `darwin` instead of `osx` so why not just find the right constant in ghc that will be `osx` in this case?

**Comment by DanielG** [comment]
Oh and either repo is fine. I maintain both of them but usually just use this one for preparing releases (and rebasing util I like it) and pushing to kazu's once everything is ready. As a rule of thumb just go with kazu's I'd ask to rebase on top of mine if there are any significant conflicts.

**Comment by abhinav** [comment]
Gave the Cabal source a quick glance. It appears that [`display`](https://downloads.haskell.org/~ghc/7.8-latest/docs/html/libraries/Cabal-1.18.1.5/Distribution-Text.html#v:display)[` buildPlatform`](https://downloads.haskell.org/~ghc/7.8-latest/docs/html/libraries/Cabal-1.18.1.5/Distribution-System.html#v:buildPlatform) gives a more reliable constant to work with for `ghc-mod`'s purposes. It's used in `cabal-install` to construct the package DB directory name.

```{.haskell}
sandboxPackageDBPath :: FilePath -> Compiler -> Platform -> String
sandboxPackageDBPath sandboxDir compiler platform =
    sandboxDir
         </> (Text.display platform ++ "-"
             ++ showCompilerIdWithAbi compiler
             ++ "-packages.conf.d")
```

So I added the `ghcSandboxPkgDbDir` function back and updated it to use the `buildPlatform` instead.

The new behavior is:

* If the directory specified by `cabal.sandbox.config` exists, always use that.
* Otherwise, try the directory that `ghcSandboxPkgDbDir` points to.
* If both approaches fail, fall back to looking for a `*-packages.conf.d` directory in the sandbox root.

**Comment by DanielG** [comment]
> - If the directory specified by cabal.sandbox.config exists, always use that.

That is not the correct behavior though, re-read my original commit message on why.

> - Otherwise, try the directory that ghcSandboxPkgDbDir points to.

> - If both approaches fail, fall back to looking for a *-packages.conf.d directory in the sandbox root.

This seems unnecessary now we know the exact path that cabal is going to use for the package-db why guess? In any case this might actually be worse as you can have package-dbs for multiple architectures and compiler versions in a single sandbox in which case this would most likely return the wrong one anyways ;)

**Comment by abhinav** [comment]
Oh, you want to account for the case where the cabal.sandbox.config points to a package DB that exists but is still incorrect? Okay. Updated.

**Comment by abhinav** [comment]
Rebased on master.

**Comment by DanielG** [comment]
This should be fixed in master now, if you feel like testing.

Do note that the relevant code will only run if you only have a sandbox in the project, so no .cabal file. That case is handled directly using Cabal now.

**Comment by abhinav** [comment]
It's using the correct path.

**Pull request closed without merging**
